name: teta_cms
description: The Dart client for Teta CMS. Our mission is to help people build amazing products.
version: 0.3.6
homepage: "https://teta.so"
repository: https://github.com/teta-so/cms
documentation: https://teta.so/flutter-docs

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  clear_response:
  light_logger:

  http: ^0.13.5
  equatable: ^2.0.3
  socket_io_client: ^2.0.0
  hive: ^2.2.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.4
  uni_links: ^0.5.1
  enum_to_string: ^2.0.1
  uuid: ^3.0.6
  universal_html: ^2.0.8
  cross_file:

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.1
