// Mocks generated by Mockito 5.3.2 from annotations
// in teta_cms/test/features/store/data/repositories/products_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;
import 'package:teta_cms/src/data_stores/local/server_request_metadata_store.dart'
    as _i7;
import 'package:teta_cms/src/features/store/data/data_sources/remote/products_api.dart'
    as _i4;
import 'package:teta_cms/src/models/server_request_metadata.dart' as _i3;
import 'package:teta_cms/teta_cms.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerRequestMetadata_1 extends _i1.SmartFake
    implements _i3.ServerRequestMetadata {
  _FakeServerRequestMetadata_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsApi extends _i1.Mock implements _i4.ProductsApi {
  MockProductsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.HttpResponse<List<_i6.TetaProduct>>> fetchProducts(
    String? authorization,
    String? projectId,
    String? contentType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [
            authorization,
            projectId,
            contentType,
          ],
        ),
        returnValue: _i5.Future<_i2.HttpResponse<List<_i6.TetaProduct>>>.value(
            _FakeHttpResponse_0<List<_i6.TetaProduct>>(
          this,
          Invocation.method(
            #fetchProducts,
            [
              authorization,
              projectId,
              contentType,
            ],
          ),
        )),
      ) as _i5.Future<_i2.HttpResponse<List<_i6.TetaProduct>>>);
  @override
  _i5.Future<_i2.HttpResponse<_i6.TetaProduct>> fetchProduct(
    String? authorization,
    String? projectId,
    String? contentType,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProduct,
          [
            authorization,
            projectId,
            contentType,
            id,
          ],
        ),
        returnValue: _i5.Future<_i2.HttpResponse<_i6.TetaProduct>>.value(
            _FakeHttpResponse_0<_i6.TetaProduct>(
          this,
          Invocation.method(
            #fetchProduct,
            [
              authorization,
              projectId,
              contentType,
              id,
            ],
          ),
        )),
      ) as _i5.Future<_i2.HttpResponse<_i6.TetaProduct>>);
  @override
  _i5.Future<_i2.HttpResponse<_i6.TetaProduct>> insertProduct(
    String? authorization,
    String? projectId,
    String? contentType,
    _i6.TetaProduct? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProduct,
          [
            authorization,
            projectId,
            contentType,
            product,
          ],
        ),
        returnValue: _i5.Future<_i2.HttpResponse<_i6.TetaProduct>>.value(
            _FakeHttpResponse_0<_i6.TetaProduct>(
          this,
          Invocation.method(
            #insertProduct,
            [
              authorization,
              projectId,
              contentType,
              product,
            ],
          ),
        )),
      ) as _i5.Future<_i2.HttpResponse<_i6.TetaProduct>>);
  @override
  _i5.Future<_i2.HttpResponse<_i6.TetaProduct>> updateProduct(
    String? authorization,
    String? projectId,
    String? contentType,
    String? id,
    _i6.TetaProduct? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            authorization,
            projectId,
            contentType,
            id,
            product,
          ],
        ),
        returnValue: _i5.Future<_i2.HttpResponse<_i6.TetaProduct>>.value(
            _FakeHttpResponse_0<_i6.TetaProduct>(
          this,
          Invocation.method(
            #updateProduct,
            [
              authorization,
              projectId,
              contentType,
              id,
              product,
            ],
          ),
        )),
      ) as _i5.Future<_i2.HttpResponse<_i6.TetaProduct>>);
  @override
  _i5.Future<_i2.HttpResponse<_i6.TetaProduct>> deleteProduct(
    String? authorization,
    String? projectId,
    String? contentType,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [
            authorization,
            projectId,
            contentType,
            id,
          ],
        ),
        returnValue: _i5.Future<_i2.HttpResponse<_i6.TetaProduct>>.value(
            _FakeHttpResponse_0<_i6.TetaProduct>(
          this,
          Invocation.method(
            #deleteProduct,
            [
              authorization,
              projectId,
              contentType,
              id,
            ],
          ),
        )),
      ) as _i5.Future<_i2.HttpResponse<_i6.TetaProduct>>);
}

/// A class which mocks [ServerRequestMetadataStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerRequestMetadataStore extends _i1.Mock
    implements _i7.ServerRequestMetadataStore {
  MockServerRequestMetadataStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ServerRequestMetadata getMetadata() => (super.noSuchMethod(
        Invocation.method(
          #getMetadata,
          [],
        ),
        returnValue: _FakeServerRequestMetadata_1(
          this,
          Invocation.method(
            #getMetadata,
            [],
          ),
        ),
      ) as _i3.ServerRequestMetadata);
  @override
  _i3.ServerRequestMetadata updateMetadata({
    String? token,
    int? prjId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMetadata,
          [],
          {
            #token: token,
            #prjId: prjId,
          },
        ),
        returnValue: _FakeServerRequestMetadata_1(
          this,
          Invocation.method(
            #updateMetadata,
            [],
            {
              #token: token,
              #prjId: prjId,
            },
          ),
        ),
      ) as _i3.ServerRequestMetadata);
}
