// Mocks generated by Mockito 5.3.2 from annotations
// in teta_cms/test/features/store/domain/use_cases/get_all_products_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:teta_cms/src/data_stores/local/server_request_metadata_store.dart'
    as _i3;
import 'package:teta_cms/src/features/store/data/data_sources/models/product_model.dart'
    as _i6;
import 'package:teta_cms/src/features/store/data/data_sources/remote/products_api.dart'
    as _i2;
import 'package:teta_cms/src/features/store/data/repositories/products_repo.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductsApi_0 extends _i1.SmartFake implements _i2.ProductsApi {
  _FakeProductsApi_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerRequestMetadataStore_1 extends _i1.SmartFake
    implements _i3.ServerRequestMetadataStore {
  _FakeServerRequestMetadataStore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepo extends _i1.Mock implements _i4.ProductsRepo {
  MockProductsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductsApi get api => (super.noSuchMethod(
        Invocation.getter(#api),
        returnValue: _FakeProductsApi_0(
          this,
          Invocation.getter(#api),
        ),
      ) as _i2.ProductsApi);
  @override
  _i3.ServerRequestMetadataStore get serverRequestMetadataStore =>
      (super.noSuchMethod(
        Invocation.getter(#serverRequestMetadataStore),
        returnValue: _FakeServerRequestMetadataStore_1(
          this,
          Invocation.getter(#serverRequestMetadataStore),
        ),
      ) as _i3.ServerRequestMetadataStore);
  @override
  _i5.Future<List<_i6.TetaProduct>> getAllProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue:
            _i5.Future<List<_i6.TetaProduct>>.value(<_i6.TetaProduct>[]),
      ) as _i5.Future<List<_i6.TetaProduct>>);
}
